sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iaflleje/isra-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true iaflleje/isra-docker dotnet test

after_success:
  - docker build -t iaflleje/isra-docker .
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push iaflleje/isra-docker
  

